import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { GQLProvider } from "@/providers/ApolloProvider";
import { AppSidebar } from "@/components/AppSidebar";
import Navbar from "@/components/Navbar";
import { SidebarProvider } from "@/components/ui/sidebar";
import ServiceWorkerRegister from "@/components/ServiceWorkerRegister";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <GQLProvider>
          <SidebarProvider>
            <div className="hidden lg:block">
              <AppSidebar />
            </div>

            <div className="flex flex-col flex-1 min-h-screen bg-slate-50/30 min-w-0">
              <Navbar />
              <main className="w-full px-3 sm:px-8 py-6 sm:py-8">
                <ServiceWorkerRegister />
                {children}
              </main>
            </div>
          </SidebarProvider>
        </GQLProvider>
      </body>
    </html>
  );
}